ZENKLU_ZODYNAS = {
    0: "Didžiausias greitis 20",
    1: "Didžiausias greitis 30",
    2: "Didžiausias greitis 50",
    3: "Didžiausias greitis 60",
    4: "Didžiausias greitis 70",
    5: "Didžiausias greitis 80",
    6: "Greičio ribojimo pabaiga",
    7: "Didžiausias greitis 100",
    8: "Didžiausias greitis 120",
    9: "Lenkti draudžiama",
    10: "Lenkti sunkvežimiams draudžiama",
    11: "Sankryža su šalutiniu keliu",
    12: "Pagrindinis kelias",
    13: "Duoti kelią",
    14: "Stop",
    15: "Eismas draudžiamas",
    16: "Sunkvežimių eismas draudžiamas",
    17: "Įvažiavimas draudžiamas",
    18: "Kiti pavojai",
    19: "Pavojingas posūkis į kairę",
    20: "Pavojingas posūkis į dešinę",
    21: "Pavojingi posūkiai",
    22: "Kelias su nelygumais",
    23: "Slidus kelias",
    24: "Kelio susiaurėjimas iš dešinės",
    25: "Kelio darbai",
    26: "Šviesoforas",
    27: "Pėsčiųjų perėja",
    28: "Vaikai",
    29: "Dviračių takas",
    30: "Kiti pavojai",
    31: "Laukiniai gyvūnai",
    32: "Apribojimų pabaiga",
    33: "Sukti į dešinę",
    34: "Sukti į kairę",
    35: "Važiuoti tiesiai",
    36: "Važiuoti tiesiai arba į dešinę",
    37: "Važiuoti tiesiai arba į kairę",
    38: "Važiuoti į dešinę",
    39: "Važiuoti į kairę",
    40: "Eismas ratu",
    41: "Lenkimo draudimo pabaiga",
    42: "Lenkimo krovininiais automobiliais draudimo pabaiga"
}
    