"""Pridėtas tikimybe į TestResult

Revision ID: 9f6ebc1d73a3
Revises: df32b386dfeb
Create Date: 2025-05-21 20:03:08.344611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f6ebc1d73a3'
down_revision = 'df32b386dfeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_rezultatai', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tikimybe', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_rezultatai', schema=None) as batch_op:
        batch_op.drop_column('tikimybe')

    # ### end Alembic commands ###
