"""Pridėtas zenklo_pavadinimas į TestResult

Revision ID: df32b386dfeb
Revises: 
Create Date: 2025-05-21 20:01:15.458003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df32b386dfeb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_rezultatai', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modelio_pavadinimas', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('atpazintas_zenklas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('zenklo_pavadinimas', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_rezultatai', schema=None) as batch_op:
        batch_op.drop_column('zenklo_pavadinimas')
        batch_op.drop_column('atpazintas_zenklas')
        batch_op.drop_column('modelio_pavadinimas')

    # ### end Alembic commands ###
